export const content = {
  nav: {
    bio: "Bio",
    strategy: "Strategy",
    investments: "Investments",
    contact: "Contact",
    brand: "KPC",
  },
  hero: {
    headline: "Partners for Capital, Intelligent Growth, Globalisation, and Strategic Innovation",
    subheadline: "Working alongside entrepreneurs to scale and globalise leading businesses.",
    learnMore: "Learn More",
  },
  home: {
    stats: {
      valueCreated: "Value Created",
      yearsExperience: "Years Experience",
      grossMoic: "Gross MOIC",
      grossIrr: "Gross IRR",
    },
    briefIntro: {
      kicker: "Buy & Build",
      text: "We partner with exceptional management teams to create leading companies in attractive sectors. Our approach focuses on long-term growth through transformation, not financial engineering.",
      cta: "Our Strategy",
    },
    featuredInvestments: {
      title: "Select Investments",
      cta: "View Track Record",
      items: {
        usj: {
          name: "Universal Studios Japan",
          description: "One of the most successful PE investments globally",
        },
        renew: {
          name: "ReNew Power",
          description: "India's largest renewable energy company",
          metric: "NASDAQ Listed",
        },
        jre: {
          name: "Japan Renewable Energy",
          description: "Japan's largest diversified renewable platform",
        },
      },
    },
    ctaBanner: {
      title: "Building something ambitious?",
      subtitle: "We'd like to hear from you.",
      cta: "Get in Touch",
    },
  },
  cookie: {
    message: "We use cookies to enhance your experience.",
    learnMore: "Learn more",
    accept: "Accept",
    decline: "Decline",
    close: "Close",
    preferences: "Cookie preferences",
  },
  legal: {
    privacy: "Privacy Policy",
    terms: "Terms of Use",
    disclaimer: "Disclaimer",
  },
  bio: {
    title: "Ankur Sahu",
    role: "Founder & Managing Partner",
    photoPlaceholder: "Photo placeholder",
    paragraph1: "Ankur Sahu is the Founder and Managing Partner of Kyoto Pacific Capital. He brings over two decades of investment experience across Asia, with a focus on Japan and India.",
    paragraph2: "Previously, Ankur served as Co-Head of Private Equity for Asia-Pacific at Goldman Sachs from 2011 to 2018, where he was a member of the Global Investment Committee, Risk Committee, and Asia Pacific Management Committee. He joined Goldman Sachs in 1998 and was appointed Managing Director in 2005 and Partner in 2006.",
    paragraph3: "During his career, Ankur led some of Asia's most pioneering investments, including Universal Studios Japan, Sanyo Electric, ReNew Power, Japan Renewable Energy, and eMobile. These investments generated over $21 billion in shareholder value creation.",
    paragraph4: "Prior to Goldman Sachs, Ankur worked at Panasonic in semiconductor design and business development roles in Japan from 1991 to 1994.",
    education: {
      title: "Education",
      text: "Ankur holds an MBA from Harvard Business School and MS in Electrical Engineering (Summa Cum Laude) from Tufts University. He currently serves on the Board of Trustees of Tufts University as Chairman of the Audit, Risk and Compliance Committee.",
    },
    personal: {
      title: "Personal",
      text: "He is fluent in English, Japanese, and Hindi. Ankur has been a member of YPO since 2007 and serves on the Executive Committee of the HBS Japan Alumni Association.",
    },
    press: "In the Press",
    cta: "Connect with Ankur",
  },
  strategyPage: {
    title: "Buy & Build",
    subtitle: "Long-term partnership for transformational growth.",
    approach: {
      title: "Our Approach",
      paragraph1: "We provide capital and expertise to companies with proven business models to accelerate their growth trajectories. We foster relationships of trust with management teams, sharing a long-term vision and business plan.",
      paragraph2: "Our focus is on growth—organic and inorganic—as the driver of value creation, rather than excessive leverage and short-term cash flow improvement. We work as co-entrepreneurs alongside management teams, leveraging our extensive experience in building and transforming businesses.",
      paragraph3: "We actively leverage technology, including data analytics and AI-driven digital transformation, to drive growth and profitability of portfolio companies.",
    },
    criteria: {
      title: "Investment Criteria",
      paragraph1: "We partner with companies primarily in Japan that are positioned to grow through differentiated organic and inorganic strategies, including expansion into India, Southeast Asia, and the Middle East.",
      paragraph2: "We seek control or joint-control positions that allow us to work closely with management teams to drive value creation. Our typical investment horizon is long-term, allowing us to make high-ROI investments and build very large businesses.",
    },
    sectors: {
      title: "Target Sectors",
      technology: { title: "Technology", description: "AI, SaaS, digital transformation, IT services and technology-enabled businesses" },
      sustainability: { title: "Sustainability", description: "Renewable energy and impact-focused sectors" },
      healthcare: { title: "Healthcare", description: "Healthcare services and pharmaceuticals" },
      consumer: { title: "Consumer", description: "Consumer brands and services" },
    },
    geography: {
      title: "Where We Invest",
      text: "Our primary focus is Japan, with expansion opportunities into India, Southeast Asia, and the Middle East. We leverage our deep networks and operational experience across these markets.",
      locations: "Japan • India • Southeast Asia • Middle East",
    },
    cta: "View Our Track Record",
  },
  investmentsPage: {
    title: "Track Record",
    subtitle: "Over $21 billion in value created across two decades.",
    stats: {
      investments: "Investments",
      capitalInvested: "Capital Invested",
      grossMoic: "Gross MOIC",
      grossIrr: "Gross IRR",
    },
    items: {
      usj: {
        name: "Universal Studios Japan",
        tag: "Entertainment",
        description: "Transformation of a theme park into one of the most successful PE investments globally. Over $7 billion of value created.",
        outcome: "Exit to Comcast",
      },
      renew: {
        name: "ReNew Power",
        tag: "Renewables",
        description: "Created India's largest and one of the world's top 15 independent renewable energy companies. 10+ GW contracted capacity.",
        outcome: "NASDAQ Listed",
      },
      jre: {
        name: "Japan Renewable Energy",
        tag: "Renewables",
        description: "Built Japan's largest diversified renewable energy platform with 900 MW capacity across solar, wind and biomass.",
        outcome: "Exit to ENEOS",
      },
      sanyo: {
        name: "Sanyo Electric",
        tag: "Industrial",
        description: "Successful turnaround of a global conglomerate with $15 billion in sales and 100,000+ employees.",
        outcome: "Exit to Panasonic",
      },
      emobile: {
        name: "eMobile",
        tag: "Telecommunications",
        description: "Created the 4th largest mobile broadband telecom operator in Japan with 4 million+ subscribers.",
        outcome: "Acquired by Softbank",
      },
      antuit: {
        name: "Antuit.ai",
        tag: "Technology",
        description: "Built a leader in AI-powered analytics solutions for demand forecasting and supply chain optimization.",
        outcome: "Acquired by Zebra Technologies",
      },
    },
    disclaimer: "Past performance is not indicative of future results. Investment experience shown represents investments led or co-led by Ankur Sahu during his tenure at Goldman Sachs (1998-2018) and at Kyoto Pacific Capital.",
    cta: "Discuss an Opportunity",
  },
  contactPage: {
    title: "Let's Talk",
    subtitle: "We're always interested in meeting exceptional founders and management teams.",
    email: "Email",
    offices: "Offices",
    officeLocations: "Japan • India",
    pitch: "Building something ambitious in Japan or India? We'd love to hear your story.",
    formTitle: "Send a Message",
    name: "Name",
    namePlaceholder: "Your name",
    emailLabel: "Email",
    emailPlaceholder: "your@email.com",
    company: "Company",
    companyPlaceholder: "Your company",
    message: "Message",
    messagePlaceholder: "Tell us about your business or inquiry",
    send: "Send Message",
    sending: "Sending...",
    responseTime: "We'll respond within 2 business days.",
    successTitle: "Message sent successfully",
    successDescription: "We'll get back to you within 2 business days.",
  },
  intro: {
    headline: "We partner with exceptional founders and management teams across Japan and India to build enduring businesses.",
    growth: {
      title: "Growth",
      description: "Partnering with exceptional businesses to accelerate their growth trajectory through strategic capital and operational expertise.",
    },
    globalisation: {
      title: "Globalisation",
      description: "Helping Asian champions expand their horizons—connecting local excellence to global opportunities.",
    },
    digital: {
      title: "Digital Transformation",
      description: "Leveraging technology and AI to modernize operations and unlock new value creation pathways.",
    },
  },
  story: {
    title: "Our Story",
    letterTitle: "A Letter from Our Founder",
    paragraph1: "After two decades at Goldman Sachs, helping build and lead the private equity business across Asia, I started Kyoto Pacific Capital with a simple idea: exceptional businesses deserve more than just capital—they deserve partners who think like entrepreneurs.",
    paragraph2: "At KPC, we work alongside founders and leadership teams to scale great companies. We do this by combining hands-on support, deep market knowledge, and the intelligent use of technology—especially where digital transformation is needed most.",
    paragraph3: "Our focus is Asia, particularly Japan and India. But our ambition is global. We help businesses grow in their home markets and beyond—because we've seen that the right mix of local trust and global perspective can create enduring impact.",
    paragraph4: "Thank you for your interest. We welcome thoughtful, values-aligned conversations—with founders, families, and fellow investors alike.",
    signature: "— Ankur Sahu",
    role: "Managing Partner",
  },
  strategy: {
    title: "Investment Strategy",
    subtitle: "Flexible capital meets focused expertise—tailored to the unique needs of each exceptional opportunity.",
    stages: {
      title: "Investment Stages",
      description: "We invest across the growth spectrum—from seed through buyout—adapting our approach to match each opportunity's unique requirements.",
      items: ["Seed & Early Stage", "Growth Capital", "Buyout & Control"],
    },
    geographies: {
      title: "Geographies",
      description: "Deep roots in Asia's most dynamic economies, with a vision for global impact.",
      items: ["Japan", "India", "Global Expansion"],
    },
    themes: {
      title: "Investment Themes",
      description: "We focus on three interconnected themes that drive lasting value creation.",
      items: ["Growth Acceleration", "Globalization", "AI & Digital Transformation"],
    },
  },
  portfolio: {
    title: "Portfolio",
    subtitle: "A selection of the exceptional businesses we've had the privilege to partner with.",
    all: "All Investments",
    current: "Current",
    past: "Past",
  },
  contact: {
    title: "Contact",
    subtitle: "We welcome thoughtful conversations with founders, families, and fellow investors.",
    formTitle: "Send a Message",
    name: "Name",
    namePlaceholder: "Your name",
    email: "Email",
    emailPlaceholder: "you@example.com",
    company: "Company",
    companyPlaceholder: "Your company (optional)",
    message: "Message",
    messagePlaceholder: "How can we help?",
    send: "Send Message",
    sending: "Sending...",
    emailLabel: "Email",
    officeLabel: "Office",
    office: "Tokyo, Japan",
  },
  footer: {
    tagline: "Working alongside entrepreneurs to scale and globalise leading businesses across Japan, India, United States, and Europe.",
    quickLinks: "Quick Links",
    aboutUs: "About Us",
    portfolio: "Portfolio",
    contact: "Contact",
    copyright: "Kyoto Pacific Capital. All rights reserved.",
  },
  backToHome: "Back to Home",
};